import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import BasicnavigationHeader from "@/components/NextUi/BasicnavigationHeader/App";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";
import MobileFooter from "@/components/MobileFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <BasicnavigationHeader />
          <div className="md:grid grid-cols-3 h-4/5">
            <Sidebar />
            <div>
              <main className="md:min-w-[800px] mb-[60px]">
                {children}
              </main>
              <Footer />
            </div>
          </div>
          <MobileFooter />
        </Providers>
      </body>
    </html>
  );
}
