import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import MobileFooter from "@/components/MobileFooter";
import BasicnavigationHeader from "@/components/NextUi/BasicnavigationHeader/App";
import Sidebar from "@/components/Sidebar";
import { ToastProvider } from "@/context/ToastContect";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ToastProvider>
            <BasicnavigationHeader />
            {/* <div className="md:grid grid-cols-3 h-4/5"> */}
            {/* <Sidebar /> */}
            <div>
              {/* <main className="md:min-w-[1200px] mb-[60px]"> */}
              {children}
              {/* </main> */}
              <Footer />
            </div>
            {/* </div> */}
            <MobileFooter />
          </ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
